[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/inbox"
  to = "/inbox.html"
  status = 200
